# Generated by Django 5.1.1 on 2024-09-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_delete_tasks_task_unique_title_per_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='time_start',
        ),
    ]
